### ISSUE TITLE
Helm for gitlab runners

### ISSUE THREAD

**Issue by moali87** [nickkadams/terraform-aws-ecs#1]
This is a cool repo, awesome work.  How do you suppose this differs from gitlab runner helm charts?  I suppose with this I can have more granular control on what the runners can access.

TBH: I just wanted to say "Hi" :)

**Comment by nickkadams** [comment]
Filing an issue to say hello :) For sake of thoroughness, GitLab helm charts are for Kubernetes so this is a good use case for existing ECS users vs EKS. The other advantage to the ECS model with Fargate, there are short-lived task definitions and not a full-time compute cluster and management control plane to pay for. Just a small t2/t3 instance to manage the docker fargate driver scheduling on ECS.
